# Generated by Django 2.1.3 on 2018-11-29 20:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClassTeacherMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine.ClassRoom')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='subject',
            name='dep',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='scode',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='sem',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='sname',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='dep',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='tid',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='tname',
        ),
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='join_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='post',
            field=models.CharField(choices=[('Professor', 'Professor'), ('Assistant Professor', 'Assistant Professor'), ('Senior Professor', 'Senior Professor')], default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='title',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.')], default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine.Semester'),
        ),
        migrations.AddField(
            model_name='group',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine.Section'),
        ),
        migrations.AddField(
            model_name='classteachermapping',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine.Department'),
        ),
        migrations.AddField(
            model_name='classteachermapping',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine.Section'),
        ),
        migrations.AddField(
            model_name='classteachermapping',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine.Teacher'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='routine.Department'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='classteachermapping',
            unique_together={('teacher', 'section')},
        ),
    ]
