# Generated by Django 2.1.3 on 2018-12-01 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0002_auto_20181201_0808'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='period',
            unique_together={('start_time', 'end_time')},
        ),
    ]
