# Generated by Django 2.1.3 on 2018-11-29 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0002_auto_20181130_0224'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('department', 'semester')},
        ),
    ]
