# Generated by Django 2.1.3 on 2018-11-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0003_auto_20181130_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='post',
            field=models.CharField(choices=[('Professor', 'Professor'), ('Assistant Professor', 'Assistant Professor'), ('Senior Professor', 'Senior Professor')], max_length=50),
        ),
    ]
