# Generated by Django 2.1.3 on 2018-11-30 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0006_periods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.')])),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='is_lab',
            field=models.BooleanField(default=False),
        ),
        migrations.RenameModel(
            old_name='Periods',
            new_name='Period',
        ),
        migrations.RenameModel(
            old_name='Group',
            new_name='SectionGroup',
        ),
        migrations.AddField(
            model_name='routine',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine.Period'),
        ),
        migrations.AddField(
            model_name='routine',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine.Section'),
        ),
        migrations.AddField(
            model_name='routine',
            name='section_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine.SectionGroup'),
        ),
        migrations.AddField(
            model_name='routine',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine.Subject'),
        ),
        migrations.AddField(
            model_name='routine',
            name='taught_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine.Teacher'),
        ),
    ]
