# Generated by Django 2.1.3 on 2018-11-30 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0007_auto_20181130_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='day',
            field=models.IntegerField(choices=[(1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday'), (7, 'Saturday')]),
        ),
        migrations.AlterField(
            model_name='routine',
            name='section_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='routine.SectionGroup'),
        ),
    ]
