# Generated by Django 2.1.3 on 2018-11-30 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0008_auto_20181130_1027'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='routine',
            unique_together={('day', 'period', 'section', 'taught_by')},
        ),
    ]
