# Generated by Django 2.1.3 on 2018-11-30 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0009_auto_20181130_1036'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='routine',
            unique_together={('day', 'period', 'section'), ('period', 'taught_by')},
        ),
    ]
