# Generated by Django 2.1.3 on 2018-11-30 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0010_auto_20181130_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='routine',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='routinedetails',
            name='routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine.Routine'),
        ),
        migrations.AddField(
            model_name='routinedetails',
            name='section_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='routine.SectionGroup'),
        ),
        migrations.AddField(
            model_name='routinedetails',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine.Subject'),
        ),
        migrations.AddField(
            model_name='routinedetails',
            name='taught_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine.Teacher'),
        ),
        migrations.RemoveField(
            model_name='routine',
            name='section_group',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='taught_by',
        ),
    ]
