# Generated by Django 2.1.3 on 2018-11-30 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0011_auto_20181130_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routinedetails',
            name='routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='routine.Routine'),
        ),
    ]
