# Generated by Django 2.1.3 on 2018-11-30 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0012_auto_20181130_1121'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('name', 'department', 'semester')},
        ),
    ]
