# Generated by Django 2.1.3 on 2018-11-30 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0013_auto_20181130_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='routine.Section'),
        ),
        migrations.AlterField(
            model_name='sectiongroup',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='routine.Section'),
        ),
    ]
