# Generated by Django 2.1.3 on 2018-11-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0014_auto_20181130_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='number',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='day',
            field=models.IntegerField(choices=[(2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday'), (7, 'Saturday')]),
        ),
    ]
